# resk start "action"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Resk Gister - create gists for your tutorial.
        uses: maticzav/resk@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
# resk end "action"
